### ISSUE TITLE
if liquibook suitable to reconstruct orderbook from FAST?

### ISSUE THREAD

**Issue by javapowered** [objectcomputing/liquibook#4]
I'm not sure if this is the right place to ask general, not directly related to code, questions. I'm sorry if it is not so (probably you can suggest newsgroup or something?)

I want to use liquibook for constructing orderbook from FAST. This means that i don't need to do "matching" because it already did by exchange, instead I only need to process and "aggregate" such structures:

struct OrderUpdate {
    int32_t instrumentId;
    uint32_t MDEntryID;
    uint32_t MDUpdateAction;      // 0 - New 1 - Change 2 -Delete
    int64_t MDEntryPx_Mantissa;
    int16_t MDEntryPx_Exponent;
    int64_t MDEntrySize_Mantissa;
    int16_t MDEntrySize_Exponent;
    uint32_t RptSeq;
    uint32_t MDEntryTime;
    uint32_t OrigTime;
    int32_t SecurityTradingStatus;
    char MDEntryType;    // 0 - buy; 1 - sell;
    char MsgType;
};

If liquibook is suitable for such work and probably any suggestions how exactly it should be used? Thanks!

**Comment by dale-wilson** [comment]
> I'm not sure if this is the right place to ask general, not directly related to code, questions. I'm sorry if it is not so (probably you can suggest newsgroup or something?)

Thanks for asking.  OCI now has a mail list for asking these kinds of questions.  It's actually one that was originally set up for QuickFAST, but over time the mFAST people have been using it so we repurposed it  to be a general list for OCI supplied support for the financial comunity.

You can join that list here: https://groups.google.com/forum/#!forum/quickfast_users

> I want to use liquibook for constructing orderbook from FAST. This means that i don't need to do "matching" because it already did by exchange, instead I only need to process and "aggregate" such structures:

It appears to me that you want to build an order book based on incoming market data.   That's a different problem from the one Liquibook is intended to solve.   Liquibook would be used by an exchange (or exchange simulator) to do order matching, rather than a trader to keep track of the state of the market.   

[sales-pitch] If you contact us at sales@objectcomputing.com we can discuss other ways to meet your needs [/sales-pitch]
